name: balzax
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip:
    - flax==0.4.1
    - jax==0.3.7
    - jaxlib==0.3.7
    - matplotlib==3.5.1
    - numpy==1.22.3
    - optax==0.1.2
